### ISSUE TITLE
Huge Ram Consumption

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#140]
Hi,
I was experiencing a huge consumption of memory while running my bots (+1GB each), so I started investigating and I created a simple echo bot using the example code provided in the repository. 
Unfortunately, I was able to reproduce the issue: I got 1GB of ram usage even from that.
I attach:
+ The zip with the `testBot`, it just needs the `bot.token` in the `resources` folder and it should start
+ A screenshot of my activity monitor showing the JVM eating up RAM.

Do you know why this happens?
Cheers
[testBot.zip](https://github.com/apimorphism/telegramium/files/6658680/testBot.zip)
![telegramiumRamConsumption](https://user-images.githubusercontent.com/4698396/122122569-e4574080-ce24-11eb-9425-f9d22d7ffd6d.png)

**Comment by johnspade** [comment]
Hello!

JVM may reserve memory according to default Xmx settings. I don't think that the example bot actually uses this much memory. You can limit it with `-Xmx256m`, for example.

**Comment by benkio** [comment]
By adding these 2 options
```
fork := true
run / javaOptions += "-Xmx256m"
```
to `build.sbt` I got this 
![image](https://user-images.githubusercontent.com/4698396/122127388-fcca5980-ce2a-11eb-8fe2-9f8273a94418.png)

I guess that, to avoid the burden of `sbt` you need to create jars files for your project and launch them.
Thanks for the support
