### ISSUE TITLE
WebhookBot HttpApp Composition

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#143]
Hi,
I open this issue to request the ability to compose multiple WebhookBot together in a single server/bot.
It should be possible by just composing the HttpApp + setWebhook requests.

The scenario where this is useful is when multiple bots have to be deployed on a single server that exposes a single ip:port pair.
There's a workaround/hack that consists of using Http4s routing and implements a reverse proxy applying different ports to each bot, but would be cool to have this available through the library itself. Otherwise, a `BindException` will be thrown.

**Comment by benkio** [comment]
I've started having a look at this. I think I will soon be able to rise a PR ;)

**Comment by benkio** [comment]
@johnspade what do you think about this?

**Comment by johnspade** [comment]
Well, I prefer to deploy my bots in separate Docker containers, but it's an interesting use case. I'll look into it.

**Comment by benkio** [comment]
> Well, I prefer to deploy my bots in separate Docker containers, but it's an interesting use case. I'll look into it.

I see, but consider that this it's just an additional capability the library enable. It doesn't go in conflict with what's already there
