### ISSUE TITLE
Write more example bots using more API methods.

### ISSUE THREAD

**Issue by sherzodv** [apimorphism/telegramium#2]

**Comment by oybek** [comment]
here is the one: https://github.com/oybek/playcs_bot

**Comment by sherzodv** [comment]
Nice, thank you. Added to README.

**Comment by oybek** [comment]
and another one) https://github.com/oybek/gdetram

**Comment by johnspade** [comment]
Great, added to README as well.

**Comment by benkio** [comment]
I also built 3 bots that rely on an infrastructure Jar, that depends on telegramium.
https://github.com/benkio/myTelegramBot/tree/master/telegrambotinfrastructure

This is the inner jar. Feel free to add it to the README
Cheers
