### ISSUE TITLE
Question: is it a good idea to add a getParticipant method?

### ISSUE THREAD

**Issue by cookienaut** [apimorphism/telegramium#307]
Hello! I want to discuss the idea about adding a new method [getParticipant](https://core.telegram.org/method/channels.getParticipant) to telegramium. As I see in telegram documentation, [bots can use this method](https://core.telegram.org/method/channels.getParticipant#bots-can-use-this-method). And, only as an example, not as a reference, some js library exposes it as well: [gramjs](https://painor.gitbook.io/gramjs/working-with-channels-and-supergroups-and-geogroups/channels.getparticipant).

If no one minds, I'd like to take on this task.

**Comment by johnspade** [comment]
Hello, that is a method from MTProto (Telegram client API) and this library is for the Telegram Bot API with the documentation at https://core.telegram.org/bots/api

**Comment by cookienaut** [comment]
So, is there any options to include that `getParticipant` method into library? Maybe another package for methods allowed for bots but that are not in Bot API?

**Comment by cookienaut** [comment]
As I see [in docs](https://core.telegram.org/api/bots#login):
```
After successful authorization, you will be able to use most MTProto API methods, just as any normal user.
Methods that can be called by bots will have a Bots can use this method notice.
```
So this flow is ok for telegram. If you don't want to include those methods to `bots` module, maybe it is possible to add another module for allowable for bots-methods and publish it separately?

**Comment by johnspade** [comment]
It would be a whole new library, I don't think it makes sense as a Telegramium module
