### ISSUE TITLE
Webook Bot server over SSL

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#348]
Hi,
Looking at [this](https://github.com/apimorphism/telegramium/blob/1dac1cbee527b4ca65ec9e348e080b22c3f393f0/telegramium-high/src/main/scala/telegramium/bots/high/WebhookBot.scala#L156) and [this](https://github.com/apimorphism/telegramium/blob/1dac1cbee527b4ca65ec9e348e080b22c3f393f0/telegramium-high/src/main/scala/telegramium/bots/high/WebhookBot.scala#L185)

I see there's no way to specify the SSL key related to the input [certificate](https://github.com/apimorphism/telegramium/blob/1dac1cbee527b4ca65ec9e348e080b22c3f393f0/telegramium-high/src/main/scala/telegramium/bots/high/WebhookBot.scala#L43) for the bot webhook HTTP server
Ideally, there should be a way to set the HTTPS server via [withSSLContext](https://github.com/apimorphism/telegramium/blob/1dac1cbee527b4ca65ec9e348e080b22c3f393f0/telegramium-high/src/main/scala/telegramium/bots/high/WebhookBot.scala#L43) 

A temporary workaround should be possible by redirecting HTTPS traffic to the HTTP server, but it defile the purpose of the SSL certificate all together.

**Comment by johnspade** [comment]
I usually prefer setting up HTTPS for my bots using Nginx and Letsencrypt, but I agree that this should be implemented. I'll look into it.

**Comment by johnspade** [comment]
And of course, PRs are welcome!

**Comment by benkio** [comment]
That's exactly how I set up the bots to support HTTPS for now. 
Thank for your reply 🙏
