### ISSUE TITLE
Method.sendGame() not working if chatId > MaxInt (2 147 483 647)

### ISSUE THREAD

**Issue by nmdaniil** [apimorphism/telegramium#395]
```chatId=6_000_000_000``` // this > MaxInt (2 147 483 647)
```sendGame(chatId.toInt, ...)```

When attempting to send a game using the sendGame method with a chatId parameter as an integer, an error is thrown: ```telegramium.bots.high.FailedRequest: method=sendGame code=400 description=Bad Request: chat not found.```

Proposed Solution:
Update the sendGame method to accept a ChatId parameter instead of an integer for the chatId argument:

```
  def sendGame(
    chatId: Int, ---> chatId: chatId
    ...
  )
```

**Comment by johnspade** [comment]
Thank you for the report, I'll fix it soon
