### ISSUE TITLE
No support for reactions?

### ISSUE THREAD

**Issue by Dessix** [apimorphism/telegramium#453]
There appears to be no exposed API for [messages.sendReaction](https://core.telegram.org/method/messages.sendReaction) or examples of similar behaviour. Is this supported indirectly?

I want to automatically acknowledge messages directed toward the bot in group-chats using reactions.

**Comment by Dessix** [comment]
In attempting to implement this and add a PR for it myself, I discovered that this is somehow an actual limitation of the Telegram Bot API. I have no idea how this was overlooked in their design, but the issue is tracked at tdlib/telegram-bot-api#260 and is filed as a bug on [the Telegram tracker](https://bugs.telegram.org/c/12710).

Closing this myself.

**Comment by johnspade** [comment]
Yes, unfortunately it's still not in the Telegram Bot API, even though it's one of the most requested features.
