### ISSUE TITLE
Proposal: change exec return type to F[Either[Throwable, A]]

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#92]
At the moment, if the telegram API returns some exception and the client forget to handle it, the whole program will crash. Therefore, I would suggest to change the singnature of `exec` method to return an `F[Either[Throwable, A]]`, so the client knows about this danger and is forced to handle it. I know it's a breaking change, but I think it's worth it, what do you think? At least it could be specified into the Readme.md.

ps: the change is easy: it's just a `.attempt`

**Comment by johnspade** [comment]
Hello!

We don't want to force users to handle all API errors, and it would lead to awkward signatures like `Either[Throwable, Either[Boolean, Message]]`. But I agree, we can handle all uncaught errors in LongPollBot/WebhookBot to avoid crashes.

Also you can define your custom `MethodSyntax`:
```scala
final class MethodSyntax[Res](private val method: Method[Res]) extends AnyVal {
  def exec[F[_]](implicit api: Api[F], monadError: MonadError[F, Throwable]): F[Either[Throwable, Res]] =
  api.execute(method).attempt
}
```
